name: The Uploader?
on:
  schedule:
    - cron:  '*/5 * * * *'
  repository_dispatch:
    types: [start-build-workflow]
  workflow_dispatch:

jobs:
  build:
    name: Build file
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
      - name: Install Dependencies
        run: npm install @actions/core mongoose fs
      - name: Build
        env:
          MONGODB_URI: ${{secrets.MONGODB_URI}}
        uses: ./
        id: build
      - name: push file
        run: |
          git config user.name Compiler
          git config user.email github-actions@github.com
          git add . || true
          git commit -m "Build" && git push || true