name: Database Sync Task
on:
    schedule:
        - cron: '*/30 * * * *'
    repository_dispatch:
        types: [start-build-workflow]
    workflow_dispatch:

jobs:
    SyncDatabase:
        name: BSync Database
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 20

            - name: Sync
              env:
                  SPECIAL_KEY: ${{secrets.SPECIAL_KEY}}
              uses: ./
              id: build

            - name: push file
              run: |
                  git config user.name "Database Sync Task"
                  git config user.email "action@github.com"
                  git add . || true
                  git commit -m "Sync Database" && git push || true
